### PR TITLE
Fix invalid syntax in book example

### PR DESCRIPTION
**Pull request by solson**
It looks like a C programmer managed to infiltrate the documentation. :slightly_smiling_face:

### CODE REVIEW

**Review by yoshuawuyts — APPROVED** [review]
lmao, great catch. Thanks!

**Comment by palfrey** [comment]
This should build ok now #303 is in

**Comment by solson** [comment]
How do we re-run the Travis CI build?

**Comment by solson** [comment]
I rebased onto master and we have a new unrelated problem on the nightly build.

**Comment by solson** [comment]
This typo still exists, but `failure` has been deprecated, so I'm closing.

**Pull request closed without merging**
